modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
issueTrackerURL="https://github.com/TelepathicGrunt/FullStackWatchdog/issues" #optional
license="https://github.com/TelepathicGrunt/FullStackWatchdog/blob/latest-released/LICENSE"

[[mods]] #mandatory
modId="fullstackwatchdog" #mandatory
logoFile= "../fullstackwatchdog_logo_wide.png"
logoBlur=false
version="${version}" #mandatory
displayName="FullStack Watchdog" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/fullstack-watchdog"
authors="TelepathicGrunt"
description='''
Makes watchdog print the entire stacktrace of every thread because truncating stacktraces is stupid.
'''

[[dependencies.fullstackwatchdog]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,)"

[[dependencies.fullstackwatchdog]]
    modId="forge"
    mandatory=true
    versionRange="(37.0.0,)"