modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
issueTrackerURL="https://github.com/TelepathicGrunt/FullStackWatchdog/issues" #optional
license="https://github.com/TelepathicGrunt/FullStackWatchdog/blob/latest-released/LICENSE"

[[mods]] #mandatory
modId="fullstackwatchdog" #mandatory
logoFile= "fullstackwatchdog_logo_wide.png"
logoBlur=false
version="${version}" #mandatory
displayName="FullStack Watchdog" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/fullstack-watchdog"
authors="TelepathicGrunt"
description='''
Makes watchdog print the entire stacktrace of every thread because truncating stacktraces is stupid.
'''

[[mixins]]
    config = "fullstackwatchdog-common.mixins.json"

[[dependencies.fullstackwatchdog]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"